version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpassword
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_HOST=0.0.0.0
    volumes:
      - ./n8n-data:/home/node/.n8n   # <-- bind mount for sharing
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  n8n_data: